version: '3.8'

services:
  db:
    build:
      context: .
    container_name: deal_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Use named volume for data persistence
      - ./backups:/backups # For storing backups
      - ./init:/docker-entrypoint-initdb.d # Mount init scripts
    environment:
      - POSTGRES_DB=deals_db
      - POSTGRES_USER=deals_user
      - POSTGRES_PASSWORD=deals_password
    # Backups: see backup_db.sh script in ./backups

  db_backup:
    build:
      context: ./backups
    container_name: deal_app_db_backup
    volumes:
      - ./backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db

volumes:
  postgres_data: 