version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8008:8008" # Host port 8008 mapped to container port 8008
    volumes:
      - .:/app # Mount app code for hot-reloading (dev)
    environment:
      - DATABASE_NAME=deals_db
      - DATABASE_USER=deals_user
      - DATABASE_PASSWORD=deals_password
      - DATABASE_HOST=172.178.68.8
      - DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  event_processing_agent:
    build:
      context: .
      dockerfile: agents/event_processing_agent/Dockerfile
    container_name: deal_event_agent
    volumes:
      - ./logs:/app/logs:rw # Mount logs directory with read-write permissions
    environment:
      - DATABASE_NAME=deals_db
      - DATABASE_USER=deals_user
      - DATABASE_PASSWORD=deals_password
      - DATABASE_HOST=172.178.68.8
      - DATABASE_PORT=5432
      - API_HOST=app
      - API_PORT=8008
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped # Automatically restart the container unless it is explicitly stopped 

  event_sourcing_agent:
    build:
      context: .
      dockerfile: Dockerfile.event_sourcing_agent
    container_name: deal_event_sourcing_agent
    volumes:
      - ./logs:/app/logs:rw # Mount logs directory with read-write permissions
    environment:
      - DATABASE_NAME=deals_db
      - DATABASE_USER=deals_user
      - DATABASE_PASSWORD=deals_password
      - DATABASE_HOST=172.178.68.8
      - DATABASE_PORT=5432
      - DATABASE_NAME_2=deals_db
      - DATABASE_USER_2=deals_user
      - DATABASE_PASSWORD_2=deals_password
      - DATABASE_HOST_2=172.178.68.8
      - DATABASE_PORT_2=5432
      - SERPAPI_KEY=${SERPAPI_KEY} # Will be taken from host environment
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped # Automatically restart the container unless it is explicitly stopped 